#! /bin/bash
set -e
set -x

bootisoks_wd='work/bootisoks'
nfs_mnt='work/mnt'
#unmount the ISO
if [ -d $bootisoks_wd ]; then
    if [ $(mountpoint -q $bootisoks_wd; echo $?) == 0 ]; then
        umount $bootisoks_wd
    fi
fi

# unmount the nfs share
if [ -d $nfs_mnt ]; then
    if [ $(mountpoint -q $nfs_mnt; echo $?) == 0 ]; then
        umount $nfs_mnt
    fi
fi

# cleanup
rm work -rf