#! /bin/bash
set -e
set -x

bootiso_wd='work/bootiso'
nfs_mnt='work/mnt'
#unmount the ISO
if [ -d $bootiso_wd ]; then
    if [ $(mountpoint -q $bootiso_wd; echo $?) == 0 ]; then
        umount $bootiso_wd
    fi
fi

# unmount the nfs share
if [ -d $nfs_mnt ]; then
    if [ $(mountpoint -q $nfs_mnt; echo $?) == 0 ]; then
        umount $nfs_mnt
    fi
fi

# cleanup
rm work -rf