#! /bin/bash
set -e
set -x

bootisoks_wd='work/bootisoks'
nfs_mnt='work/mnt'
#unmount the ISO
if [ -d $bootisoks_wd ]; then
    umount $bootisoks_wd
fi

# unmount the nfs share
if [ -d $nfs_mnt ]; then
    umount $nfs_mnt
fi

# cleanup
rm work -rf