#! /bin/bash

set -e
set -x

# download dependencies
apt install nfs-common genisoimage -y

# Create the working and mount directories
mkdir -p work/bootiso

ovirt_latest_url="http://jenkins.ovirt.org/job/ovirt-node-ng_master_build-artifacts-el7-x86_64/lastSuccessfulBuild/artifact/exported-artifacts/"

# find the latest ovirt iso version
ovirt_iso_name_tr=$(curl $ovirt_latest_url/latest-installation-iso.html | grep -o '".*"' -m1)
ovirt_iso_name=${ovirt_iso_name_tr//\"}
# join iso name and url


# Download the ISO artifact from the ovirt jenkins link.
curl $ovirt_latest_url/$ovirt_iso_name -o work/$ovirt_iso_name
  
# Mount the iso
mount -o loop work/$ovirt_iso_name work/bootiso
# Create the iso working folder and copy the contents of the ISO there.
mkdir work/bootisoks
cp -r work/bootiso/* work/bootisoks/

# Mod permissions
chmod -R u+w work/bootisoks

# Copy the isolinux.cfg file to a seperate workspace.
cp work/bootisoks/isolinux/isolinux.cfg work/isolinux.cfg

# Add stage2 and ks cfg
sed -i \
  's/inst.stage2=hd:LABEL=CentOS\\x207\\x20x86_64//' \
  work/isolinux.cfg
sed -i \
  's/inst.ks=hd:LABEL=CentOS\\x207\\x20x86_64:\/interactive-defaults.ks/inst.ks=http:\/\/nas1.magiccityit.com\/ovirt-node-isos\/ovirt_node-ks.cfg inst.stage2="http:\/\/mirror.centos.org\/centos\/7\/os\/x86_64\/"/' \
  work/isolinux.cfg
# Clean up extra params
sed -i \
  's/quiet//' work/isolinux.cfg
sed -i \
  's/rd.live.check//' work/isolinux.cfg
sed -i \
  's/nomodeset//' work/isolinux.cfg

# Copy config to iso filesystem.
yes | cp work/isolinux.cfg work/bootisoks/isolinux/isolinux.cfg -f

# Create ISO
cd work/bootisoks && genisoimage -o $ovirt_iso_name -b isolinux.bin -c boot.cat \
  -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -v -T isolinux/. .

cd ..
# mount nfs drive
mkdir mnt/
mount -t nfs nfs1.magiccityit.com:/data-volume/ovirt-node-isos/ mnt/
ovirt_iso_path=${ovirt_iso_name:0:-4}
if [ ! -d "mnt/$ovirt_iso_path" ]; then
  mkdir mnt/$ovirt_iso_path
fi
cp bootisoks/ovirt-node-ng-image.squashfs.img mnt/$ovirt_iso_path/ovirt-node-ng-image.squashfs.img
cp bootisoks/$ovirt_iso_name mnt/$ovirt_iso_path/$ovirt_iso_name

# create json object
echo "{'iso_file_name': $ovirt_iso_name,'squashfs_file_name': 'ovirt-node-ng-image.squashfs.img', 'iso_file_url': \"http://nas1.magiccityit.com/ovirt-node-isos/$ovirt_iso_path\" }" > ovirt_iso_env.json
cp ovirt_iso_env.json  mnt/ovirt_iso_env.json